
spring.datasource.hikari.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.jdbc-url=jdbc:mysql://3.12.15.1:3306/insight?useUnicode=true&charactersetEncoding=utf8
spring.datasource.hikari.username=javaspringstudy
spring.datasource.hikari.password=thatkxkd123
spring.datasource.hikari.connection-test-query=SELECT 1