spring.datasource.hikari.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.hikari.jdbc-url=jdbc:mysql://3.12.15.1/javaspringstudy?useUnicode=true&characterEncoding=utf-8
spring.datasource.hikari.username=javaspringstudy
spring.datasource.hikari.password=thatkxkd123
spring.datasource.hikari.connection-test-query=SELECT 1
spring.main.allow-bean-definition-overriding=true

mybatis.configuration.map-underscore-to-camel-case=true