### member join test
POST http://localhost:8080/member/join
Content-Type: application/json

{
  "username": "test2",
  "password": "test1",
  "name": "이름",
  "email": "d@d.com"
}

### normal
GET http://localhost:8080/nice/test

### login test
POST http://localhost:8080/member/login
Content-Type: application/json

{
  "username": "test2",
  "password": "test1"
}

### authorization test
GET http://localhost:8080/nice/auth
Cookie: JSESSIONID=F4121314078141B38E5718227E6F335B;


### logout test
GET http://localhost:8080/logout
Cookie: JSESSIONID=F4121314078141B38E5718227E6F335B;