

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:qdsl
    username: sa
    password:
  sql:
    init:
      mode: always
      platform: h2
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true